--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/dropmebeat/iConomyBedrock-PocketMine
build-by-default: true
branches:
- main
projects:
  iConomyBedrock-PocketMine:
    path: ""
...
